-- Run this in your Snowflake worksheet before starting the project

CREATE DATABASE IF NOT EXISTS ANALYTICS_DB;
USE DATABASE ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS DIM_USERS (
    ID          INTEGER PRIMARY KEY,
    USERNAME    VARCHAR(255),
    EMAIL       VARCHAR(255),
    CREATED_AT  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_CONTENT (
    ID          INTEGER PRIMARY KEY,
    USER_ID     INTEGER,
    TITLE       VARCHAR(500),
    CREATED_AT  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FACT_EVENTS (
    ID          INTEGER PRIMARY KEY,
    USER_ID     INTEGER,
    CONTENT_ID  INTEGER,
    EVENT_TYPE  VARCHAR(50),
    TIMESTAMP   TIMESTAMP
);
